# DeltaRedis Configuration File

# Login and connection information for the Redis server
RedisServer:
  URL: localhost
  Port: 6379
  HasPassword: False
  Password: DeltaRedis_Is_Great!

# Name        | Type
# ------------------------
# MrRoboto    | BungeeCord
# Diamond     | Spigot
# Gold        | Spigot
# Iron        | Spigot

# Name of the BungeeCord instance to which the server belongs.
# From the example, this should be set to 'MrRoboto'.
BungeeName: Bungee

# Exact name of the server as listed in the BungeeCord config.
# This name is case-sensitive! Please double check to make sure it is correct.
# From the example, it should be 'Diamond', 'Gold' or 'Iron'.
ServerNameInBungeeCord: World

# Time in ticks for every online server and online player update
OnlineUpdatePeriod: 300

# Used for debugging DeltaRedis
DebugMode: True
